### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by helihyv** [jakekall/shortest-path#1]
ZIP ladattu 19.8. klo 17.08.

Koodi on erittäin selkeää ja helppolukuista. Luokkarakenne on selkeä ja toimiva. Pakkausrakenne on muuten selkeä, mutta tietorakenteet ja apufunktioluokat voisivat ehkä olla omissa pakkauksissaan.

Molemmat reitinhakualgoritmit vaikuttivat hyvin toteutetuilta. Omat toteutukset keosta ja hajautustaulusta vain vielä puuttuvat.

MathUtil-luokassa on vielä käytössä javan valmiita luokkia/funktioita. Liukulukujen yhtäsuuruutta selvitettäessä voisi valmiit java.Math.BigDecimal ja java.Math.RoundingMode -luokat korvata laskemalla tutkittavien lukujen erotuksen itseisarvon ja vertaamalla sitä haluttuun rajaan yhtäsuuriksi tulkitsemiselle. Saman luokan hypot()-funktiossa piitäisi muistaa korvata Math.hypot() -funktio laskemalla hypotenuusa itse.

StringUtil-luokasssa on subString funktiossa yhä käytössä javan System.arraycopy, vaikka. taulukon kopioimiseen on jo toteutettu oma apufunktio. Saman luokan funktiot toInt ja parseInt eivät vielä tee muuta kuin kutsuvat javan vastaavaa funktiota. 

Koska reitinhaku kestää melko pitkään, voisi käyttöliittymään lisätä jonkilaisen "searching route..." -tyyppisen tulostuksen ennen haun aloittamista, jotta käyttäjä ei jäisi ihmettelemään miksei mitään vielä tapahdu.
 
Algoritmien suorituskyvystä voisi tulostaa enemmänkin vertailutietoja. Esimerkiksi hakuaikojen ja /tai eri algoritmien nopeuserojen samassa haussa hajonnat olisivat kiinnostavia. 

Reitinhakualgoritmien testit testaavat nyt vain vaaka- ja pystysuoraan kulkemista kapeassa käytävässä joka ei haaraudu. Kannattaisi testata myös tilanteita, joissa mahdollisa kuljettavia reittejä on useampi, jotta algoritmit joutuvat valitsemaan useamman kuin yhden mahdollisen tulosuunnasta poikkeavan kaaren välillä. Etenkin reittiä, jolla nopein reitti kulkee vinoittain vaikka vaaka -ja pystysuoraankin pääsisi perille, kannattaisi testata. Siinä tulisi testatuksi myös tilanne, jossa verkossa on eripainoisia kaaria.   

Yleisesti ottaen oikein siistiä koodia ja toimiva ohjelma.

**Comment by jakekall** [comment]
Kiitos hyvistä vinkeistä. 👍
